---

# our globals.yml is in the "config" dir under our site config
# CONFIG_DIR is set by --configdir
site_config_base: "{{ CONFIG_DIR }}/.."

# The directory on the deploy host containing globals.yml.
# this is part of our site config
node_config: "{{ CONFIG_DIR }}"

# The directory to merge custom config files the kolla's config files
node_custom_config: "{{ CONFIG_DIR }}../node_custom_config"

# The directory to store the config files on the destination node
node_config_directory: "/opt/kolla/config"
virtualenv: /opt/kolla/venv

# The group which own node_config_directory, you can use a non-root
# user to deploy kolla
config_owner_user: "ubuntu"
config_owner_group: "ubuntu"



# defined in kolla/group_vars/all.yml
kolla_install_type: source
kolla_base_distro: ubuntu

# point at the docker registry we want
openstack_release: train
docker_namespace: kolla
docker_registry: docker.chameleoncloud.org



# network config
kolla_internal_vip_address: 10.0.110.254
kolla_external_vip_address: 10.0.100.254

# neutron_bridge_name: defaults to br-ex

# might need to set this in group/host-vars instead
neutron_external_interface: ens7
